### ISSUE TITLE
Invalid CSS declaration “font:bold”

### ISSUE THREAD

**Issue by bignose-debian** [ichord/At.js#540]
The CSS file ‘jquery.atwho.css’ contains an [invalid declaration for the `font` property](https://github.com/ichord/At.js/blob/master/src/jquery.atwho.css#L51):

```css
.atwho-view .cur strong {
    color: white;
    font:bold;
}
```

The value `bold` is not valid for the `font` property. Many browsers will (correctly) ignore this invalid declaration.

**Comment by bignose-debian** [comment]
This should probably be a declaration of [the `font-weight` property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) instead:

```css
.atwho-view .cur strong {
    color: white;
    font-weight: bold;
}
```
